### ISSUE TITLE
Todo checklist before submission 

### ISSUE THREAD

**Issue by fbartolic** [fbartolic/volcano#18]
- [x] Change plots to include full model prediction (including GP) and binned data
- [x] Finish conclusions section
- [x] Incorporate feedback from @dfm and @rodluger  
- [x] Incorporate feedback from Robert
- [x] Move some of the math into appendices
- [ ] Fix build on azure.

@dfm @rodluger anything else?
